### ISSUE TITLE
Future announcement - Beiwe will eventually be changing some endpionts

### ISSUE THREAD

**Issue by biblicabeebli** [harvard-nrg/mano#4]
(Hi Tim!)

There are some updates to the Beiwe data access endpoints that I'm going to get to in the currently-distant future.  Wondering if I could get repo access for when I eventually get to those.

(Probably new /v2 targets, possible credentialing changes, and possibly adding compression back in to data access - that last one is not trivial.)

**Comment by biblicabeebli** [comment]
(also, after reviewing this, I would like to link it from the beiwe documentation.)

**Comment by tokeefe** [comment]
Absolutely. Just sent you an invite with commit privs.

**Comment by biblicabeebli** [comment]
I'm in.

*evil cackling....*

I will get to this at some point, no changes to the api are staged anywhere beyond my skull right now.  Probsbly will use this test side effects on some refactoring I intend to do before any feature upgrades.  Your call on closing this issue.

**Comment by tokeefe** [comment]
Sweet. When you do have the new /v2 targets implemented, let me know. I'm going to close this issue.
